Downloader improvements and make offline development possible
ParchmentMC/Compass pull request #22
Opened 2023-05-03 17:03 UTC by qwertyuioplkjhgfd

2023-05-03 17:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ParchmentMC/Compass?pullRequest=22) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ParchmentMC/Compass?pullRequest=22) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ParchmentMC/Compass?pullRequest=22) it.</sub>

2023-05-08 16:26 UTC, marchermans requested changes

2023-05-08 16:26 UTC, marchermans commented on src/main/java/org/parchmentmc/compass/util/download/ManifestsDownloader.java
> +            }
This is not a good idea, at least with regards to the launcher manifest, it should be downloaded at all times, only if gradle is offline should it be skipped.

2023-05-08 16:50 UTC, sciwhiz12 requested changes
In addition to @marchermans's point, our download utility is backed by the [gradle-download-task](https://github.com/michel-kraemer/gradle-download-task) plugin, which I believe supports Gradle's native offline mode (`--offline` through the CLI; Eclipse and IntelliJ support it too).

The reason I didn't put those output file existence checks when writing the download utility originally is because that would mean needing to manually delete the manifests when they change remotely, as otherwise it would always skip the download action if the manifest exists. As you can see in the beginning of [`DownloadUtil#createAndExecuteAction`](https://github.com/ParchmentMC/Compass/blob/d1416a404d89ad3992776e121715fcc7aad7b4b7/src/main/java/org/parchmentmc/compass/util/download/DownloadUtil.java#L19-L21), it is configured to always check the remote source for changes (using ETags) and download only if there are changes.

The only change I have no hesitance about is the change in `DownloadUtil#createAndExecuteAction` that makes it catch all exceptions and appends the output path to the exception message.

2023-05-08 17:21 UTC, char3210 commented
yeah that makes sense, for some reason I was having some trouble having it work with intellij's offline mode. should the check for `VersionDownload` still be checked though, since it checks the hash?

2023-08-05 17:53 UTC, sciwhiz12 approved these changes

2023-08-05 17:54 UTC, merged

2023-08-05 17:56 UTC, sciwhiz12 commented
> should the check for `VersionDownload` still be checked though, since it checks the hash?

Sorry for not addressing this earlier. The check should be fine, as the hash of the file in the version manifest should only really change if the file changes on the server, which we then redownload. When the hash doesn't change (which is 99% the scenario), the file didn't change, so no need to query the server for that same info.